version: "3.5"
services:
  midi2mp3-api:
    image: weesee/midi2mp3-api:1.0
    build: ./
    volumes:
      - ./lib:/var/www/lib:delegated
      - ./public://var/www/public:delegated
    ports:
      - '8094:80'
